# This is a config for E2B sandbox template.
# You can use template ID (ofyiazitxrx32w23cgbu) or template name (vibe-nextjs-ccpp1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-ccpp1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-ccpp1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-ccpp1')

team_id = "a1f42594-e5f8-4d2a-a9fc-8ae488d4e47d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-ccpp1"
template_id = "ofyiazitxrx32w23cgbu"
