import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
   
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>

<<<<<<< HEAD
<<<<<<< HEAD
    
=======
   
>>>>>>> e1ed815f1386464be7226be2078749dc1882af3f
=======
   
>>>>>>> e1ed815f1386464be7226be2078749dc1882af3f
    <html lang="en"
    suppressHydrationWarning
    >
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
<<<<<<< HEAD
<<<<<<< HEAD
    </TRPCReactProvider>
=======
     </TRPCReactProvider>
>>>>>>> e1ed815f1386464be7226be2078749dc1882af3f
=======
     </TRPCReactProvider>
>>>>>>> e1ed815f1386464be7226be2078749dc1882af3f
  );
}
